# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nrf52840_mdk_usb_dongle
    shield: urchin_dongle
    artifact-name: urchin-dongle
  - board: nice_nano_v2
    shield: urchin_left nice_view_adapter nice_view
    artifact-name: urchin-left
  - board: nice_nano_v2
    shield: urchin_right nice_view_adapter nice_view
    artifact-name: urchin-right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings-reset